tunnel: 108a7249-2632-44e2-bebc-6718b31c0de3
credentials-file: /home/asdasd/.cloudflared/108a7249-2632-44e2-bebc-6718b31c0de3.json

ingress:
    - hostname: sieg.dev
      service: http://127.0.0.1:8081
    - service: http_status:404
